# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

# This workflow performs a build of the project and uploads the result as a build artifact.

name: Reusable MSBuild Workflow

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      # repository to be used (needed for self-hosted runner setups)
      repository:
        required: true
        type: string
      # Name associated with the output of this build.
      build_artifact:
        required: true
        type: string
      # Additional options passed to msbuild.
      build_options:
        required: false
        type: string
      configurations:
        required: false
        type: string
        default: '["Debug", "Release"]'

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 90

    strategy:
      matrix:
        configurations: ${{ fromJSON(inputs.configurations) }}

    runs-on: windows-2022
    env:
      # Path to the solution file relative to the root of the project.
      SOLUTION_FILE_PATH: ctsTraffic.sln
      BUILD_ARTIFACT_NAME: ${{inputs.build_artifact}}
      BUILD_CONFIGURATION: ${{matrix.configurations}}
      BUILD_PLATFORM: x64
      BUILD_OPTIONS: ${{inputs.build_options}}
      CXX_FLAGS: ${{inputs.cxx_flags}}
      LD_FLAGS: ${{inputs.ld_flags}}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      if: steps.skip_check.outputs.should_skip != 'true'
      with:
        repository: ${{inputs.repository}}
        submodules: 'recursive'
        ref: ${{inputs.ref}}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2

    - name: Nuget Restore
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      run: msbuild /p:Configuration=${{matrix.configurations}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.BUILD_OPTIONS}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        name: ${{env.BUILD_ARTIFACT_NAME}} ${{env.BUILD_CONFIGURATION}}
        path: 'x64/${{env.BUILD_CONFIGURATION}}'

    